# Site settings
site: waterStone
title: waterStone blog
keywords: Bitcoin, blog, programming
description: >-
  waterStone blog
lang: en-US
timezone:  Europe/Istanbul
repo: # site repo [optional]https://github.com/waterst0ne.waterst0ne.github.io // not needed afterall
google_verify:      XXX # Put your Google Verification here
google_analytics:   UA-XXXXXXXX-00 # Put your Google Analytics code
discus-identifier:  XXX

# Author settings
author:
  name: waterStone
  bio: Computer Science @parallelogos <br> Bitcoin Contributor @BitcoinDevKit <br> Open Source /#linux
  picture: assets/images/profile.jpg 
  github: waterst0ne # github username
  twitter: parallelogos # twitter username
  facebook: # facebook username
  instagram:  # instagram username
  youtube:  # youtube username
  email: # email adress


# URL settings
url:  # Domain Name of host. [username].github.io for github pages // doesn't need it after all
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false